Homework 3
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.4     ✓ stringr 1.4.0
    ## ✓ readr   2.0.2     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(viridis)
```

    ## Loading required package: viridisLite

``` r
library(p8105.datasets)
library(dplyr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

First, we need to load the `instacart` data.

``` r
data("instacart")
```

The `instacart` data has 15 variables and 1384617 observations. The
variables include order_id, product_id, add_to_cart_order, reordered,
user_id, eval_set, order_number, order_dow, order_hour_of_day,
days_since_prior_order, product_name, aisle_id, department_id, aisle,
department. Among these, eval_set, product_name, aisle, and department
are character variables, and the others are numerical variables.

### How many aisles are there, and which aisles are the most items ordered from?

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarize(n_obs = n()) %>% 
  arrange(desc(n_obs))
```

    ## # A tibble: 134 × 2
    ##    aisle                          n_obs
    ##    <chr>                          <int>
    ##  1 fresh vegetables              150609
    ##  2 fresh fruits                  150473
    ##  3 packaged vegetables fruits     78493
    ##  4 yogurt                         55240
    ##  5 packaged cheese                41699
    ##  6 water seltzer sparkling water  36617
    ##  7 milk                           32644
    ##  8 chips pretzels                 31269
    ##  9 soy lactosefree                26240
    ## 10 bread                          23635
    ## # … with 124 more rows

There are `134` aisles. The most items ordered form the
`fresh vegetables` aisle, and the number of orders from this aisle is
150609.

### Plotting the number of items ordered in each aisle with more than 10000 items ordered.

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarize(n_obs = n()) %>% 
  arrange(desc(n_obs)) %>% 
  filter(n_obs > 10000) %>% 
  ggplot(aes(x = aisle, y = n_obs)) +
  geom_point() +
  labs(
    title = "The Number of Items Ordered in Each Aisle", 
    x = "Aisles", 
    y = "The number of items ordered"
  ) + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1))
```

<img src="p8105_hw3_xj2278.Rmd-_files/figure-gfm/unnamed-chunk-3-1.png" width="90%" />

The scatter plot shows the number of items order in each aisle, which
these aisles are those has more than 10000 items ordered.

### The three most popular items in “baking ingredients”, “dog food care”, and “packaged vegetables fruits”

``` r
baking = instacart %>% 
  filter(aisle %in% "baking ingredients") %>% 
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  arrange(desc(n)) %>% 
  filter(rank <= 3) 

dog = instacart %>% 
  filter(aisle %in% "dog food care") %>% 
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  arrange(desc(n)) %>% 
  filter(rank <= 3) 

veg = instacart %>% 
  filter(aisle %in% "packaged vegetables fruits") %>% 
  group_by(aisle) %>%
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  arrange(desc(n)) %>% 
  filter(rank <= 3) 

Q3 = bind_rows(baking, dog, veg) %>% 
  subset(select = -rank) %>% 
  knitr::kable()
```

The table shows that for `baking ingredients`, the top three popular
items are `light brown sugar`, `pure baking soda`, and `cane sugar`, and
the corresponding times of order are 499, 387, and 336; for
`dog food care` aisle, the top three popular items are
`Snack Sticks Chicken & Rice Recipe Dog Treats`,
`Organix Chicken & Brown Rice Recipe`, and `Small Dog Biscuits`, and the
corresponding times of order are 30, 28, and 26; for
`packaged vegetables fruits` aisle, the top three popular items are
`organic baby spinach`, `organic raspberries`, and
`organic blueberries`, and their corresponding times of order are 9784,
5546, and 4966.

### The mean hour at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week

``` r
Q4 = 
  instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(mean_order_hour = mean(order_hour_of_day)) %>% 
  mutate(order_dow = recode(order_dow, `0` = "Sunday", `1` = "Monday", `2` = "Tuesday", `3` = "Wednesday", `4` = "Thurday", `5` = "Friday", `6` = "Saturday")) %>% 
  pivot_wider(
    names_from = order_dow,
    values_from = mean_order_hour
  ) %>% 
  knitr::kable()
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

The table shows that
